-- MOUS business accounts (M-14) and new messaging channels (M-12).
--
-- MOUS accounts are email + password accounts kept by the MOUS worker (passwords are hashed with
-- PBKDF2 and stay in Workers KV — never in this database). They are not Supabase Auth users, so
-- mous_businesses.user_id (references auth.users) can't hold them: this adds a mous_accounts table
-- and mous_businesses.owner_account_id instead.
--
-- Written only by the MOUS worker with the service-role key; RLS on with no policies.

create table if not exists public.mous_accounts (
  id uuid primary key,                         -- the account id generated by the worker
  email text not null unique,
  created_at timestamptz default now()
);

alter table public.mous_businesses
  add column if not exists owner_account_id uuid references public.mous_accounts(id) on delete set null;
create index if not exists mous_businesses_owner on public.mous_businesses (owner_account_id);

-- Instagram and Messenger conversations (M-12) are mirrored to mous_calls too.
alter table public.mous_calls drop constraint if exists mous_calls_channel_check;
alter table public.mous_calls add constraint mous_calls_channel_check
  check (channel in ('voice', 'whatsapp', 'web', 'demo', 'public', 'instagram', 'messenger'));

alter table public.mous_accounts enable row level security;
